# Generated by Django 4.1.2 on 2022-10-20 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('tarea', models.CharField(max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=10)),
                ('fechafin', models.DateTimeField(blank=True, null=True)),
                ('importante', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
